// Presents the policy popup when an AI interaction requires user acknowledgement.
const WINDOW_FEATURES = 'width=420,height=620,resizable=yes,scrollbars=yes';

// Hooks popup request events so the policy dialog appears when required.
export async function init(context = {}) {
	// Respond to popup requests generated by metadata tracking.
	const { runtime } = context;

	const handler = (event) => {
		const { popupUrl } = event.detail || {};
		if (!popupUrl) {
			return;
		}

		const url = resolveUrl(popupUrl, runtime);
		openPopup(url);
	};

	window.addEventListener('ai-popup-requested', handler);

	return () => {
		window.removeEventListener('ai-popup-requested', handler);
	};
}

// Converts a popup resource path into a fully qualified extension URL.
function resolveUrl(popupUrl, runtime) {
	if (runtime && typeof chrome !== 'undefined' && chrome?.runtime?.getURL) {
		return chrome.runtime.getURL(popupUrl);
	}

	return popupUrl;
}

// Safely opens the policy window while reporting unexpected failures.
function openPopup(url) {
	try {
		window.open(url, 'aiUsageWarning', WINDOW_FEATURES);
	} catch (error) {
		console.error('[aiUsageIntervention] Failed to open popup', error);
	}
}
